"""Hardware abstraction protocols for fluid transfer units."""

from typing import Protocol


class TransferPump(Protocol):
    """Variable-speed pump with safety interlock awareness."""

    def set_speed(self, speed: float) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def get_current_speed(self) -> float: ...


class FlowGate(Protocol):
    """On/off flow gate (e.g. solenoid valve)."""

    def on(self) -> None: ...
    def off(self) -> None: ...
    def is_active(self) -> bool: ...


class PulseFlowSensor(Protocol):
    """Pulse-counting flow sensor."""

    def start_counting(self, pulse_limit: int) -> None: ...
    def stop_counting(self) -> None: ...
    def reset_pulse_count(self) -> None: ...
    def get_pulse_count(self) -> int: ...
    def read(self) -> float: ...


class OperatorTrigger(Protocol):
    """Physical operator input (foot pedal, hold-to-run button, etc.)."""

    def read(self) -> bool: ...
